"""v2 schema with context_window

Revision ID: 0d252c912e68
Revises: 
Create Date: 2026-04-01 11:07:39.626571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d252c912e68'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('request_body', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('response_body', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_batch_log_batch_id', 'batch_log', ['batch_id'], unique=False)
    op.create_index('idx_batch_log_stage', 'batch_log', ['stage'], unique=False)
    op.create_table('message',
    sa.Column('message_ts', sa.String(), nullable=False),
    sa.Column('thread_ts', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['thread_ts'], ['message.message_ts'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('message_ts')
    )
    op.create_index('idx_message_channel', 'message', ['channel'], unique=False)
    op.create_index('idx_message_thread', 'message', ['thread_ts'], unique=False)
    op.create_table('thread_bundle',
    sa.Column('root_message_ts', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['root_message_ts'], ['message.message_ts'], ),
    sa.PrimaryKeyConstraint('root_message_ts')
    )
    op.create_table('bundle_membership',
    sa.Column('message_ts', sa.String(), nullable=False),
    sa.Column('bundle_ts', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('root', 'reply', 'continuation', name='bundle_role'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.CheckConstraint('confidence > 0.0 AND confidence <= 1.0', name='ck_confidence'),
    sa.ForeignKeyConstraint(['bundle_ts'], ['thread_bundle.root_message_ts'], ),
    sa.ForeignKeyConstraint(['message_ts'], ['message.message_ts'], ),
    sa.PrimaryKeyConstraint('message_ts')
    )
    op.create_index('idx_membership_bundle', 'bundle_membership', ['bundle_ts'], unique=False)
    op.create_table('context_window',
    sa.Column('bundle_ts', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('compressed', sa.Boolean(), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bundle_ts'], ['thread_bundle.root_message_ts'], ),
    sa.PrimaryKeyConstraint('bundle_ts')
    )
    op.create_index('idx_cw_channel', 'context_window', ['channel'], unique=False)
    op.create_index('idx_cw_compressed', 'context_window', ['compressed'], unique=False)
    op.create_index('idx_cw_created', 'context_window', ['created_at'], unique=False)
    op.create_table('atom',
    sa.Column('atom_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('DECISION', 'SPEC_CHANGE', 'ACTION_ITEM', 'BLOCKER', 'RISK', 'TEST_RESULT', 'STATUS_UPDATE', 'QUESTION', name='atom_type'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('urgency', sa.Enum('low', 'medium', 'high', 'critical', name='urgency_level'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('implicit_decision', sa.Boolean(), nullable=False),
    sa.Column('source', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_bundle_ts', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_atom_confidence'),
    sa.ForeignKeyConstraint(['source_bundle_ts'], ['context_window.bundle_ts'], ),
    sa.PrimaryKeyConstraint('atom_id')
    )
    op.create_index('idx_atom_bundle', 'atom', ['source_bundle_ts'], unique=False)
    op.create_index('idx_atom_created', 'atom', ['created_at'], unique=False)
    op.create_index('idx_atom_type', 'atom', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_atom_type', table_name='atom')
    op.drop_index('idx_atom_created', table_name='atom')
    op.drop_index('idx_atom_bundle', table_name='atom')
    op.drop_table('atom')
    op.drop_index('idx_cw_created', table_name='context_window')
    op.drop_index('idx_cw_compressed', table_name='context_window')
    op.drop_index('idx_cw_channel', table_name='context_window')
    op.drop_table('context_window')
    op.drop_index('idx_membership_bundle', table_name='bundle_membership')
    op.drop_table('bundle_membership')
    op.drop_table('thread_bundle')
    op.drop_index('idx_message_thread', table_name='message')
    op.drop_index('idx_message_channel', table_name='message')
    op.drop_table('message')
    op.drop_index('idx_batch_log_stage', table_name='batch_log')
    op.drop_index('idx_batch_log_batch_id', table_name='batch_log')
    op.drop_table('batch_log')
    # ### end Alembic commands ###
