"""add comments to all tables and columns

Revision ID: 90b308aa6b1b
Revises: 0d252c912e68
Create Date: 2026-04-01 23:18:52.470976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90b308aa6b1b'
down_revision: Union[str, Sequence[str], None] = '0d252c912e68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('atom', 'atom_id',
               existing_type=sa.UUID(),
               comment='UUID primary key; generated by the pipeline, not the LLM',
               existing_nullable=False)
    op.alter_column('atom', 'type',
               existing_type=postgresql.ENUM('DECISION', 'SPEC_CHANGE', 'ACTION_ITEM', 'BLOCKER', 'RISK', 'TEST_RESULT', 'STATUS_UPDATE', 'QUESTION', name='atom_type'),
               comment='Atom type (8 types: DECISION, SPEC_CHANGE, etc.)',
               existing_nullable=False)
    op.alter_column('atom', 'summary',
               existing_type=sa.TEXT(),
               comment='One-line summary of what happened',
               existing_nullable=False)
    op.alter_column('atom', 'detail',
               existing_type=sa.TEXT(),
               comment='Expanded explanation with context and implications',
               existing_nullable=False)
    op.alter_column('atom', 'urgency',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'critical', name='urgency_level'),
               comment='Urgency: low, medium, high, or critical',
               existing_nullable=False)
    op.alter_column('atom', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='LLM extraction confidence [0.0-1.0]; halved if validation fails',
               existing_nullable=False)
    op.alter_column('atom', 'implicit_decision',
               existing_type=sa.BOOLEAN(),
               comment='Whether this decision was implicit (stated without formal agreement)',
               existing_nullable=False)
    op.alter_column('atom', 'source',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Provenance JSONB: channel, thread_ts, message_range, key_participants',
               existing_nullable=False)
    op.alter_column('atom', 'source_bundle_ts',
               existing_type=sa.VARCHAR(),
               comment='FK to context_window; which LLM input produced this atom',
               existing_nullable=False)
    op.alter_column('atom', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this atom was extracted and persisted',
               existing_nullable=False)
    op.create_table_comment(
        'atom',
        'Extracted information atoms with LLM provenance and scoring metadata',
        existing_comment=None,
        schema=None
    )
    op.alter_column('batch_log', 'id',
               existing_type=sa.INTEGER(),
               comment='Auto-increment primary key',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('batch_log', 'batch_id',
               existing_type=sa.VARCHAR(),
               comment='Anthropic batch ID (e.g. msgbatch_01...)',
               existing_nullable=False)
    op.alter_column('batch_log', 'stage',
               existing_type=sa.VARCHAR(),
               comment='Pipeline stage: extraction_stage1, extraction_stage2, validation',
               existing_nullable=False)
    op.alter_column('batch_log', 'request_count',
               existing_type=sa.INTEGER(),
               comment='Number of individual requests in this batch',
               existing_nullable=False)
    op.alter_column('batch_log', 'status',
               existing_type=sa.VARCHAR(),
               comment='Final batch status: submitted, processing, ended, canceled, errored',
               existing_nullable=False)
    op.alter_column('batch_log', 'request_body',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Full JSON request body sent to Anthropic Batch API',
               existing_nullable=False)
    op.alter_column('batch_log', 'response_body',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Full JSON response body from Anthropic; NULL until batch completes',
               existing_nullable=True)
    op.alter_column('batch_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the batch was submitted to Anthropic',
               existing_nullable=False)
    op.alter_column('batch_log', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the batch finished processing; NULL if still running',
               existing_nullable=True)
    op.create_table_comment(
        'batch_log',
        'Audit log for Anthropic Batch API requests/responses',
        existing_comment=None,
        schema=None
    )
    op.alter_column('bundle_membership', 'message_ts',
               existing_type=sa.VARCHAR(),
               comment='FK to message; a message belongs to exactly one bundle',
               existing_nullable=False)
    op.alter_column('bundle_membership', 'bundle_ts',
               existing_type=sa.VARCHAR(),
               comment='FK to thread_bundle; which bundle this message belongs to',
               existing_nullable=False)
    op.alter_column('bundle_membership', 'role',
               existing_type=postgresql.ENUM('root', 'reply', 'continuation', name='bundle_role'),
               comment='Role: root (thread starter), reply (explicit), or continuation (semantic match)',
               existing_nullable=False)
    op.alter_column('bundle_membership', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Match confidence: 1.0 for structural, cosine similarity for semantic',
               existing_nullable=False)
    op.alter_column('bundle_membership', 'ordinal',
               existing_type=sa.INTEGER(),
               comment='Position within the bundle (0-indexed, chronological)',
               existing_nullable=False)
    op.create_table_comment(
        'bundle_membership',
        'Maps messages to thread bundles with role, confidence, and ordering',
        existing_comment=None,
        schema=None
    )
    op.alter_column('context_window', 'bundle_ts',
               existing_type=sa.VARCHAR(),
               comment='FK to thread_bundle; 1:1 relationship (one window per bundle)',
               existing_nullable=False)
    op.alter_column('context_window', 'channel',
               existing_type=sa.VARCHAR(),
               comment='Channel where the source thread lives',
               existing_nullable=False)
    op.alter_column('context_window', 'compressed',
               existing_type=sa.BOOLEAN(),
               comment='Whether the window was compressed to fit within LLM token limits',
               existing_nullable=False)
    op.alter_column('context_window', 'raw',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Full context window as JSONB: thread_text, message_range, token estimate',
               existing_nullable=False)
    op.alter_column('context_window', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this context window was assembled',
               existing_nullable=False)
    op.create_table_comment(
        'context_window',
        'Assembled text windows sent to the LLM for atom extraction',
        existing_comment=None,
        schema=None
    )
    op.alter_column('message', 'message_ts',
               existing_type=sa.VARCHAR(),
               comment='Slack message timestamp, unique ID within a channel',
               existing_nullable=False)
    op.alter_column('message', 'thread_ts',
               existing_type=sa.VARCHAR(),
               comment='Parent thread timestamp; NULL for top-level messages',
               existing_nullable=True)
    op.alter_column('message', 'channel',
               existing_type=sa.VARCHAR(),
               comment='Slack channel name with # prefix (e.g. #chassis-design)',
               existing_nullable=False)
    op.alter_column('message', 'user_id',
               existing_type=sa.VARCHAR(),
               comment='Slack user ID of the message author (e.g. U001)',
               existing_nullable=False)
    op.alter_column('message', 'raw',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Full Slack API message payload as JSONB for replay/debugging',
               existing_nullable=False)
    op.create_table_comment(
        'message',
        'Raw Slack messages ingested from the API or fixture data',
        existing_comment=None,
        schema=None
    )
    op.alter_column('thread_bundle', 'root_message_ts',
               existing_type=sa.VARCHAR(),
               comment='Root message timestamp; also FK to message table',
               existing_nullable=False)
    op.alter_column('thread_bundle', 'channel',
               existing_type=sa.VARCHAR(),
               comment='Channel where this thread lives',
               existing_nullable=False)
    op.alter_column('thread_bundle', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this bundle was first persisted to Postgres',
               existing_nullable=False)
    op.create_table_comment(
        'thread_bundle',
        'Thread bundles grouping related messages into conversational units',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'thread_bundle',
        existing_comment='Thread bundles grouping related messages into conversational units',
        schema=None
    )
    op.alter_column('thread_bundle', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this bundle was first persisted to Postgres',
               existing_nullable=False)
    op.alter_column('thread_bundle', 'channel',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Channel where this thread lives',
               existing_nullable=False)
    op.alter_column('thread_bundle', 'root_message_ts',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Root message timestamp; also FK to message table',
               existing_nullable=False)
    op.drop_table_comment(
        'message',
        existing_comment='Raw Slack messages ingested from the API or fixture data',
        schema=None
    )
    op.alter_column('message', 'raw',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Full Slack API message payload as JSONB for replay/debugging',
               existing_nullable=False)
    op.alter_column('message', 'user_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Slack user ID of the message author (e.g. U001)',
               existing_nullable=False)
    op.alter_column('message', 'channel',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Slack channel name with # prefix (e.g. #chassis-design)',
               existing_nullable=False)
    op.alter_column('message', 'thread_ts',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Parent thread timestamp; NULL for top-level messages',
               existing_nullable=True)
    op.alter_column('message', 'message_ts',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Slack message timestamp, unique ID within a channel',
               existing_nullable=False)
    op.drop_table_comment(
        'context_window',
        existing_comment='Assembled text windows sent to the LLM for atom extraction',
        schema=None
    )
    op.alter_column('context_window', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this context window was assembled',
               existing_nullable=False)
    op.alter_column('context_window', 'raw',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Full context window as JSONB: thread_text, message_range, token estimate',
               existing_nullable=False)
    op.alter_column('context_window', 'compressed',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether the window was compressed to fit within LLM token limits',
               existing_nullable=False)
    op.alter_column('context_window', 'channel',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Channel where the source thread lives',
               existing_nullable=False)
    op.alter_column('context_window', 'bundle_ts',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='FK to thread_bundle; 1:1 relationship (one window per bundle)',
               existing_nullable=False)
    op.drop_table_comment(
        'bundle_membership',
        existing_comment='Maps messages to thread bundles with role, confidence, and ordering',
        schema=None
    )
    op.alter_column('bundle_membership', 'ordinal',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Position within the bundle (0-indexed, chronological)',
               existing_nullable=False)
    op.alter_column('bundle_membership', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Match confidence: 1.0 for structural, cosine similarity for semantic',
               existing_nullable=False)
    op.alter_column('bundle_membership', 'role',
               existing_type=postgresql.ENUM('root', 'reply', 'continuation', name='bundle_role'),
               comment=None,
               existing_comment='Role: root (thread starter), reply (explicit), or continuation (semantic match)',
               existing_nullable=False)
    op.alter_column('bundle_membership', 'bundle_ts',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='FK to thread_bundle; which bundle this message belongs to',
               existing_nullable=False)
    op.alter_column('bundle_membership', 'message_ts',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='FK to message; a message belongs to exactly one bundle',
               existing_nullable=False)
    op.drop_table_comment(
        'batch_log',
        existing_comment='Audit log for Anthropic Batch API requests/responses',
        schema=None
    )
    op.alter_column('batch_log', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the batch finished processing; NULL if still running',
               existing_nullable=True)
    op.alter_column('batch_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the batch was submitted to Anthropic',
               existing_nullable=False)
    op.alter_column('batch_log', 'response_body',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Full JSON response body from Anthropic; NULL until batch completes',
               existing_nullable=True)
    op.alter_column('batch_log', 'request_body',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Full JSON request body sent to Anthropic Batch API',
               existing_nullable=False)
    op.alter_column('batch_log', 'status',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Final batch status: submitted, processing, ended, canceled, errored',
               existing_nullable=False)
    op.alter_column('batch_log', 'request_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of individual requests in this batch',
               existing_nullable=False)
    op.alter_column('batch_log', 'stage',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Pipeline stage: extraction_stage1, extraction_stage2, validation',
               existing_nullable=False)
    op.alter_column('batch_log', 'batch_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Anthropic batch ID (e.g. msgbatch_01...)',
               existing_nullable=False)
    op.alter_column('batch_log', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Auto-increment primary key',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'atom',
        existing_comment='Extracted information atoms with LLM provenance and scoring metadata',
        schema=None
    )
    op.alter_column('atom', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this atom was extracted and persisted',
               existing_nullable=False)
    op.alter_column('atom', 'source_bundle_ts',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='FK to context_window; which LLM input produced this atom',
               existing_nullable=False)
    op.alter_column('atom', 'source',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Provenance JSONB: channel, thread_ts, message_range, key_participants',
               existing_nullable=False)
    op.alter_column('atom', 'implicit_decision',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether this decision was implicit (stated without formal agreement)',
               existing_nullable=False)
    op.alter_column('atom', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='LLM extraction confidence [0.0-1.0]; halved if validation fails',
               existing_nullable=False)
    op.alter_column('atom', 'urgency',
               existing_type=postgresql.ENUM('low', 'medium', 'high', 'critical', name='urgency_level'),
               comment=None,
               existing_comment='Urgency: low, medium, high, or critical',
               existing_nullable=False)
    op.alter_column('atom', 'detail',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Expanded explanation with context and implications',
               existing_nullable=False)
    op.alter_column('atom', 'summary',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='One-line summary of what happened',
               existing_nullable=False)
    op.alter_column('atom', 'type',
               existing_type=postgresql.ENUM('DECISION', 'SPEC_CHANGE', 'ACTION_ITEM', 'BLOCKER', 'RISK', 'TEST_RESULT', 'STATUS_UPDATE', 'QUESTION', name='atom_type'),
               comment=None,
               existing_comment='Atom type (8 types: DECISION, SPEC_CHANGE, etc.)',
               existing_nullable=False)
    op.alter_column('atom', 'atom_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID primary key; generated by the pipeline, not the LLM',
               existing_nullable=False)
    # ### end Alembic commands ###
